### ISSUE TITLE
Vue: Module not found

### ISSUE THREAD

**Issue by markusnissl** [daybrush/guides#13]
## Environments
* Framework name: Vue
* Framework version: 2.x

## Description
I installed vue-guides via npm. Then I included it like in the description.
However, it does not compile, I always get:
 Module not found: Error: Can't resolve 'vue-guides'

Workaround: If I go into the directory node_modules/vue-guides and build the project, then it works.

**Comment by daybrush** [comment]
@markusnissl 

Try 0.6.2 version. thank you :)

**Comment by markusnissl** [comment]
Unfortunately, it does not work.

I checked the commit history of this package, and I only find a version increase in the commit.

**Comment by daybrush** [comment]
@markusnissl 

Try 0.6.3 version. it's now work. Thank you :)
https://unpkg.com/vue-guides@0.6.3/dist/guides.cjs.js

**Comment by markusnissl** [comment]
@daybrush  thanks, it works 👍
