### ISSUE TITLE
Can you please explain to me in code how i can use other units like inches and centimetres for my rulers? 

### ISSUE THREAD

**Issue by smandepudi** [daybrush/guides#15]
I am using your guides component in my angular app used for editing text and images
I am trying ti change the units to Inches from the default pixels. The below code shows it in pixels 
I tried changing unit=1 which did not work for me. Can you please explain in code , how i can make this work for inches. thank you 
<ngx-guides #guides1 type="horizontal" unit="50" displayDragPos="true"></ngx-guides>

**Comment by daybrush** [comment]
```js
ngOnAfterInit() {
    guides1.scroll(px);
}
```

**Comment by smandepudi** [comment]
Ok this worked Thank you very much.
