### ISSUE TITLE
Remove all guides

### ISSUE THREAD

**Issue by KosF** [daybrush/guides#20]
## Environments
* Framework:
ReactJS (16.13.0)

## Description

Hi @daybrush!
Thx a lot for your guides component!
But I have one question: 
how to remove all guides after clicking on some element, e.g.:
https://prnt.sc/tlssem

**Comment by daybrush** [comment]
@KosF 
call loadGuides method
```js

guides. loadGuides([]);
```

**Comment by KosF** [comment]
awesome,
thx a lot!
