### ISSUE TITLE
Scale the ruler

### ISSUE THREAD

**Issue by KosF** [daybrush/guides#21]
## Description

Hi @daybrush!
When I scale the ruler, I get the wrong behavior when I click on the guide. Could you please advise how can I fix this?

Thanks!
[screen.mov.zip](https://github.com/daybrush/guides/files/4962732/screen.mov.zip)

**Comment by KosF** [comment]
maybe you could add `props` for this?
https://prnt.sc/tn468g

**Comment by daybrush** [comment]
@KosF 

oh If transform is applied, it is very difficult to calculate the position. If not only scale but also rotate is applied.

Let's consider the scale option as in your screenshot.

**Comment by KosF** [comment]
Within my task I need to use 'scale'. I have this value and I could pass it inside the component

**Comment by daybrush** [comment]
@KosF 

guides's new version is released.
If you just use it without options, it will work. Try it

**Comment by KosF** [comment]
@daybrush 
awesome! thanks a lot!
