### ISSUE TITLE
Guides do not follow mouse position when container is scaled

### ISSUE THREAD

**Issue by gabiap** [daybrush/guides#25]
## Environments
* Framework name: none
* Framework version: none
* Component name: demo
* Component version: https://daybrush.com/moveable/

## Description
I've noticed that whenever the container is scaled (i.e. zoom != 1), the guides do not move along with the position of the mouse:
![guides-issue](https://user-images.githubusercontent.com/24275798/93629959-d25d8400-f9f1-11ea-8bda-9752815e60c9.gif)

I've seen this issue in the demo page for the moveable project and I assumed it has to do with the guides component.

Thank you and awesome work!!

**Comment by daybrush** [comment]
@gabiap 


Thank you. The guides and demos were fixed.

**Comment by gabiap** [comment]
Awesome!
