### ISSUE TITLE
It seems like the latest version is 0.12.1, But It isn't published to npm repo

### ISSUE THREAD

**Issue by hamelmoon** [daybrush/guides#27]
## Environments
* Framework name: Vue
* Framework version: 2.0
* Component name: vue-guides
* Component version: : 0.12.1
* Testable Address(optional): 

## Description
Thanks for your hard work!
I was trying to update from 0.10.3 to the latest to use the new feature. It seems like the latest version is 0.12.1, But It isn't published to npm repo. Repo. has the 0.11.1 version

Could you check the latest version? 0.11.1 has an error of dependency missing.

**Comment by hamelmoon** [comment]
this is an error message when I update to 0.11.1
-----------
"export 'calculateMatrixDist' was not found in 'css-to-mat'

**Comment by daybrush** [comment]
@hamelmoon 
It seems like a temporary dependency problem. Please try reinstall.

**Comment by hamelmoon** [comment]
I deleted folder of node_modules and reinstall, but message is same. 

 warning  in ./node_modules/react-compat-guides/dist/guides.esm.js
"export 'calculateMatrixDist' was not found in 'css-to-mat'

**Comment by daybrush** [comment]
@hamelmoon 

Try clearing the package-lock as well. There will be an old version of css-to-mat in the package-lock.

**Comment by hamelmoon** [comment]
in css-to-mat/declaration/CSSToMatrix.d.ts
import { MatrixInfo } from "./types";
export declare function createMatrix(): number[];
export declare function parseMat(transform: string | string[]): number[];
export declare function getElementMatrix(el: HTMLElement): number[];
export declare function caculateMatrixDist(matrix: number[], pos: number[]): number[];
export declare function getDistElementMatrix(el: HTMLElement, container?: HTMLElement): number[];
export declare function toMat(matrixInfos: MatrixInfo[]): number[];
export declare function parse(transform: string | string[]): MatrixInfo[];

I think there is a typo. 'l'
caculateMatrixDist -> calculateMatrixDist

**Comment by daybrush** [comment]
@hamelmoon 

I updated css-to-mat and corrected typos in that area. Your css-to-mat doesn't seem to have been updated.

**Comment by hamelmoon** [comment]
I didn't explicitly use css-to-mat in pakage.json. I only installed and used vue-guides. To fix the error, I explicitly added the css-to-mat dependency in pakage.json. Thanks for the help.
