### ISSUE TITLE
textColor Setting the font color has no effect

### ISSUE THREAD

**Issue by clevergod** [daybrush/guides#3]

**Comment by daybrush** [comment]
@clevergod 

I want to know the framework name, framework version, component name, component version you use.

**Comment by clevergod** [comment]
@daybrush 
To clarify, I really like your library

version： "@scena/guides": "^0.4.1"

I ran your demo and had the same problem
![image](https://user-images.githubusercontent.com/21006901/71948641-a73c5700-320b-11ea-934b-81f9cc67b9e1.png)

**Comment by clevergod** [comment]
"name": "@scena/ruler",
 "version": "0.2.0",

I tried this is ok

**Comment by daybrush** [comment]
@clevergod 

I'm sorry. The preact-ruler in preact-guides is now 1.7. I didn't upgrade to 2.0.

I'll update you this evening.

try `npm i preact-ruler` temporarily?

**Comment by daybrush** [comment]
@clevergod 

`@scena/guides` 0.4.2 is released . Check it again.

If `preact-ruler` is installed, delete it first and install `@scena/ruler`
