### ISSUE TITLE
Horizontal Guide Not Rendering Properly

### ISSUE THREAD

**Issue by joncursi** [daybrush/guides#44]
## Environments
* Framework name: `react`
* Framework version: `17.0.2`
* Component name: `@scena/react-guides`
* Component version: `0.16.0`

## Description

After upgrading from `@scena/react-guides` version `0.14.0` --> `0.16.0`, my horizontal ruler stopped rendering/loading properly:

![Screen Shot 2021-06-15 at 9 30 15 PM](https://user-images.githubusercontent.com/4974609/122144154-e7503200-ce20-11eb-918d-e06c59cfa7b3.png)

When I manually trigger `topRulerEl.current.resize();`, the horizontal ruler then renders properly and is interactive again:

![Screen Shot 2021-06-15 at 9 31 31 PM](https://user-images.githubusercontent.com/4974609/122144248-11a1ef80-ce21-11eb-80c4-d6366325025a.png)

**Comment by daybrush** [comment]
@joncursi 

There is a possibility that the css will be mounted before loading.

In that case, you must finally call resize() after mounting.

**Comment by joncursi** [comment]
This appears to be fixed in the latest release of the library, thank you!
