### ISSUE TITLE
Reactive properties in svelte

### ISSUE THREAD

**Issue by acurrieclark** [daybrush/guides#58]
## Environments
* Framework name: svelte
* Framework version: 3.49.0
* Component name: Guides
* Component version: latest
* Testable Address(optional): https://svelte.dev/repl/fcb3ca74d65e44f4b98d5772394d5c21?version=3.49.0 

## Description
Is there a way to make properties like `zoom` and `unit` reactive? I would like to have it so that when a user zooms in, the guides scale accordingly. Couldn't find an API for updating the properties after initialiasation.

Many thanks.

**Comment by daybrush** [comment]
@acurrieclark 

svelte-guides's new version is released. Check it agian. Thank you :)

**Comment by acurrieclark** [comment]
Thanks so much for the quick turnaround. Works perfectly
