### ISSUE TITLE
Question: InfiniteViewer + Guides Pinch Zooming

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/guides#62]
## Environments
* Framework name: VanillaJS
* Component name:  Guides, Rulers, InfiniteViewer
* Component version: 0.19.0, 0.11.0, 0.17.0
* Testable Address(optional):  [CodePen](https://codepen.io/SidIcarus/pen/mdLvJMR)

## Description
When pinch zooming, the guides are very janky. I tried to replicate the setup you have in your main moveable demo and reduce it to the bare minimum to show the problem.

Any thoughts on what causes the guides positioning to not be as smooth when zooming?

**Comment by daybrush** [comment]
@SidIcarus 

Use `forceUpdate` method
```js
    verticalGuides.setState({ unit, zoom });
    horizontalGuides.setState({ unit, zoom });
  verticalGuides.forceUpdate();
  horizontalGuides.forceUpdate();
```

**Comment by SidIcarus** [comment]
Thank you!

**Comment by daybrush** [comment]
@bytasv 

I'm so sorry about that. Updating props works asynchronously, and if you want to use a canvas and draw on the canvas immediately after scrolling, you need to do it synchronously to eliminate the following phenomenon.

To be synchronous, you must call the method directly.

**Comment by daybrush** [comment]
@bytasv 

InfiniteViewer Pinch

I also used setZoom with useAutoZoom.

https://github.com/daybrush/scena/blob/master/packages/react-editor/src/Editor/editorComponents/InfiniteViewerManager.tsx#L69



Guides `zoom`
https://github.com/daybrush/scena/blob/master/packages/react-editor/src/Editor/editorComponents/GuidesManager.tsx#L22

**Comment by daybrush** [comment]
@bytasv 

Guides' new version is released. And `zoomTo` method was added.

```jsx
onPinch={(e) => {
          const zoom = e.zoom;
          horizontalGuidesRef.current.zoomTo(zoom);
          verticalGuidesRef.current.zoomTo(zoom);
          setZoom(e.zoom);
        }}
```
https://codesandbox.io/s/react-infinite-viewer-guides-fzlonn?file=/src/App.js

**Comment by daybrush** [comment]
@bytasv 

Oh, Sorry. Guides's new version is released. Check it again.
