### ISSUE TITLE
Feature Request: expose element references via getters

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/guides#63]
## Environments
* Framework name: VanillaJS
* Component name: guides
* Component version: 0.19.0

## Description
Expose element references via getters.
i.e `getContainer`

**Comment by daybrush** [comment]
@SidIcarus 

Okay, I'll add it soon.

**Comment by daybrush** [comment]
@SidIcarus 

* `@scena/guides` 0.20.0
* `preact-guides` 0.19.0
* `react-compat-guides` 0.17.0
* `@scena/react-guides` 0.19.0
* `svelte-guides` 0.19.0
* `vue-guides` 0.19.0
* `vue3-guides` 0.3.0
* `ngx-guides` 0.19.0

`getElement` method (Guides container element) was added.
`getRulerElement` method (ruler canvas element) was added.

**Comment by SidIcarus** [comment]
Although the function is working, I'm not seeing the type declaration in the latest release.

**Comment by daybrush** [comment]
@SidIcarus 

Oh, Sorry. guides' new version is released. Check it again.
