### ISSUE TITLE
Feature Request: Allow for scrolling when dragging guides

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/guides#64]
## Environments
* Framework name: VanillaJS
* Component name: guides
* Component version: 0.19.0

## Description

Users will then be able to implement something like the following, much like the scroll events implemented for `selecto` and `moveable`

```ts
// horizontal
  scroll (e) {
    const deltaY = e.direction[1] * scrollSpeed
    infiniteViewer.scrollBy(0, deltaY)
  }
  
  // vertical
  scroll (e) {
    const deltaX = e.direction[0] * scrollSpeed
    infiniteViewer.scrollBy(deltaX, 0)
  }
 ```

**Comment by daybrush** [comment]
@SidIcarus 

Okay, I'll add it soon.

**Comment by daybrush** [comment]
@SidIcarus 

* `@scena/guides` 0.20.0
* `preact-guides` 0.19.0
* `react-compat-guides` 0.17.0
* `@scena/react-guides` 0.19.0
* `svelte-guides` 0.19.0
* `vue-guides` 0.19.0
* `vue3-guides` 0.3.0
* `ngx-guides` 0.19.0

```js

**Comment by SidIcarus** [comment]
@daybrush 
Curious about your rationale on the decision of making the `scroll`(`requestScroll`) event handle as part of the `scrollOptions` instead of as part of the `on` events in other places (i.e `Selecto` & `Moveable`)
