### ISSUE TITLE
Bug: Dragging an existing guide to the same position as another guide does not trigger changeGuide

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/guides#65]
## Environments
* Framework name: VanillaJS
* Component name:  Guides
* Component version: 0.19.0
* Testable Address(optional): https://daybrush.com/moveable/

## Description
To reproduce
- drag a vertical or horizontal guide to position `x` (`0` is easy since it snaps)
- from the same axis, drag another guide to position `y`
- drag either of the guides to the position of the other one
- See that it does not trigger `changeGuide`

**Comment by daybrush** [comment]
@SidIcarus 


@SidIcarus 

* `@scena/guides` 0.20.0
* `preact-guides` 0.19.0
* `react-compat-guides` 0.17.0
* `@scena/react-guides` 0.19.0
* `svelte-guides` 0.19.0
* `vue-guides` 0.19.0
* `vue3-guides` 0.3.0
* `ngx-guides` 0.19.0

guides' new version is released. Check it again.
