### ISSUE TITLE
Feature Request: propagate guide `index` to emitted `changeGuides` event

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/guides#66]
## Environments
* Framework name: VanillaJS
* Component name: Guides
* Component version: 0.19.0

## Description
Since the original `inputEvent` nor `datas` is not propagated in `changeGuides` from the `drag` events, I am unable to retrieve the index from the element so I currently must do a diff of my array of guides and the current array to find which one changed. 

It looks like the index is retrieved from the guide element attribute before firing off the event `datas.target.getAttribute("data-index");`. Propagating the index would be far more performant for handling the removal or change.

**Comment by daybrush** [comment]
@SidIcarus 

* `@scena/guides` 0.20.0
* `preact-guides` 0.19.0
* `react-compat-guides` 0.17.0
* `@scena/react-guides` 0.19.0
* `svelte-guides` 0.19.0
* `vue-guides` 0.19.0
* `vue3-guides` 0.3.0
* `ngx-guides` 0.19.0


`index` property is added on changeGuides event
