### ISSUE TITLE
Bug: You are able to drag scroll from rulers when guides are hidden and element is disabled

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/guides#68]
## Environments
* Framework name: VanillaJS
* Components: 
  - "@scena/guides": "^0.20.2",
  - "@scena/ruler": "^0.12.0",
  - "infinite-viewer": "^0.18.0"
* Testable Address(optional): [codesandbox](https://codesandbox.io/s/guides-61-16m5l6?file=/src/index.ts)

## Description

To Reproduce
1. click on either rulers to add a guide and immediately drag scroll
2. Click the `Show Guides`  button (this will toggle off `showGuides`)
3. perform step 1

Notice that you are still scroll dragging with no guide or anything

**Comment by daybrush** [comment]
@SidIcarus 

Try using `pointer-events: none` on the guides element.

**Comment by SidIcarus** [comment]
I already have that style applied via this rule
```css
[disabled] {
  cursor: not-allowed;
  opacity: 0.4;
  pointer-events: none;
}
```
toggle `Show Guides` adds the `disabled` attribute to the ruler element, `scena-guides scena-vertical`.

**Comment by SidIcarus** [comment]
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/3842798/204573162-73501b91-f8cd-4f15-ba66-44e7ad866126.png">
Applying it to the child, `scena-manager scena-vertical  rCSfrxbsy`, doesn't make a difference either.

**Comment by daybrush** [comment]
@SidIcarus 


@scena/guides@0.20.3 is released.


And i checked the demo.
It doesn't seem to be dragging from Guides or InfiniteViewer.
It's just that your drag causes the scroll.

Try to set css to  `stage` element
```css
user-drag: none;
    -webkit-user-drag: none;
    user-select: none;
    -moz-user-select: none;
    -webkit-user-select: none;
    -ms-user-select: none;
```

**Comment by SidIcarus** [comment]
Oh wow, I didn't even think of that. 
Thank you!
