### ISSUE TITLE
There still has `console.log(nextPos)` in the latest version 0.23.0

### ISSUE THREAD

**Issue by nzbin** [daybrush/guides#71]
## Environments
* Framework name:
* Framework version:
* Component name: 
* Component version:
* Testable Address(optional): 

## Description

When install the latest 0.23.0, it still has `console.log` and can't find `zoomTo` prop

```ts
/*
Copyright (c) 2019 Daybrush
name: react-compat-guides
license: MIT
author: Daybrush
repository: https://github.com/daybrush/guides/blob/master/packages/react-compat-guides
version: 0.20.0
*/

...
console.log(nextPos); // => line 1254
...
```

**Comment by daybrush** [comment]
@nzbin 
Oh, Sorry. Guides' new version is released. Try it again. Thank you :)

**Comment by xoptimal** [comment]
hi @daybrush  ,  version 28.1.0 also has this issue...

Guides.tsx:90
```
 console.log(type, zoom, guidesZoom);
```

**Comment by daybrush** [comment]
@xoptimal 

guides' new version is released. Check it again.
