### ISSUE TITLE
Digit prop is missing in vue-guides

### ISSUE THREAD

**Issue by usmanpakistan** [daybrush/guides#72]
## Environments
* Framework name: VueJS
* Framework version: 2.5
* Component name: vue-guides
* Component version:  0.23.1
* Testable Address(optional): 

## Description
The "digit" prop is missing from the Vue version. Passing digit prop has no effect and appears as $attr

![3f2a73b9bccd3810466c6a34567dec9c](https://user-images.githubusercontent.com/9464992/215333265-4f8e4031-fdbd-428d-b8c2-909e956393b0.png)

**Comment by daybrush** [comment]
@usmanpakistan 

Guides' new version is released. Check it again.
