### ISSUE TITLE
Events cannot be triggered

### ISSUE THREAD

**Issue by John60676** [daybrush/guides#80]
## Environments
* Framework name: js
* Framework version: - 
* Component name:   @scena/guides 
* Component version: 0.26.1
* Testable Address(optional):  https://codesandbox.io/s/nostalgic-elbakyan-j1zsvt?file=/src/index.js

## Description

Events cannot be triggered. I also tested the Vue 3 version, and it have the same problem. Rolling back to version 0.24.0 seems to work

**Comment by daybrush** [comment]
@John60676 

* `croact-guides` 0.23.1
* `@scena/guides` 0.26.2
* `preact-guides` 0.25.1
* `@scena/react-guides` 0.25.1
* `svelte-guides` 0.25.2
* `vue-guides` 0.25.2
* `vue3-guides` 0.9.2
* `ngx-guides` 0.25.2
* 

guides' new version is released. Check it again.

**Comment by John60676** [comment]
It works
