### ISSUE TITLE
Whether the function of highlighting the specified area is supported

### ISSUE THREAD

**Issue by haixin-fang** [daybrush/guides#82]
## Environments
* Framework name:
* Framework version:
* Component name: 
* Component version:
* Testable Address(optional): 

## Description
![企业微信截图_8c2eee60-ab77-464f-8596-f403e4916f5b](https://github.com/daybrush/guides/assets/48665972/cb9c2df7-44e7-42a4-9dbe-733eb9b8ce5d)

**Comment by daybrush** [comment]
@haixin-fang 

use `selectedRanges`  prop

https://daybrush.com/guides/release/latest/doc/Guides.html#.GuideOptions-selectedRanges

```
selectedRanges={[[100, 200]]}
```
