### ISSUE TITLE
Different units for vertical & horizontal rulers

### ISSUE THREAD

**Issue by Amerlander** [daybrush/guides#83]
## Environments
* Framework name: Svelte
* Framework version:
* Component name: svelte-guides
* Component version:
* Testable Address(optional): https://svelte.dev/repl/eea47f64217144d7aa6bef6bf0c37da5?version=4.0.5

## Description
Using different units on vertical and horizontal rulers results in "switched" snapping of the guides.
The horizontal guides are fitting to the horizontal ruler, but they should fit the vertical ruler, since they are positioned vertical.

Lines placed on each snaping position:
![image](https://github.com/daybrush/guides/assets/3764089/27c7527a-f765-4ea8-ad24-786742e23f3c)

**Comment by daybrush** [comment]
@Amerlander 

moveable's new version is released.

Added `guidesZoom` property.

If not set or used as 0, it is automatically set to the same value as `zoom`.

**Comment by Amerlander** [comment]
@daybrush Thank you for the update. It's not working properly yet; when I drop a horizontal guide at 0.5, it gets placed at 4 instead.

It might also be beneficial to introduce a `guidesUnit` option to specify the behavior of the guides in detail.

https://svelte.dev/repl/69716d51b0fd498f94ebcba9a57cee25?version=4.0.5

https://github.com/daybrush/guides/assets/3764089/564595b3-9fd2-4170-9f8d-bbf39e54eadb

**Comment by daybrush** [comment]
@Amerlander 


guides' new version is released. Check it agian.

**Comment by Amerlander** [comment]
@daybrush thank you, works great now!
