### ISSUE TITLE
how to remove a guide line by double click it

### ISSUE THREAD

**Issue by leeboo** [daybrush/guides#9]
## Environments
* Framework name: Vue
* Framework version: 2.x
* Component name: 

## Description
how to remove a guide line by double click it

**Comment by daybrush** [comment]
@leeboo 

guides's new version is released. Update and Check it again. Thank you :)

**Comment by leeboo** [comment]
thank you

**Comment by daybrush** [comment]
@bytasv 

There is a bug with double click and it will be fixed.

  If you want to block remove, try setting lockGuides: ["remove"].
